package com.inclusive.finance.bean

  class ProcessHistort{
    var annex: String?=""
    var approvalOpinion: String?=""
    var beginTime: String?=""
    var createBy: String?=""
    var createDate: String?=""
    var curNodeName: String?=""
    var curNodeNo: String?=""
    var delFlag: String?=""
    var endSign: String?=""
    var endTime: String?=""
    var handler: String?=""
    var handlerCreditNo: String?=""
    var handlerNo: String?=""
    var handlerOpinion: String?=""
    var id: String?=""
    var item1: String?=""
    var item2: String?=""
    var item3: String?=""
    var item4: String?=""
    var item5: String?=""
    var operateType: String?=""
    var reject: String?=""
    var rejectCreditNo: String?=""
    var rejectNo: String?=""
    var rejectSign: String?=""
    var relationId: String?=""
    var remarks: String?=""
    var type: String?=""
    var updateBy: String?=""
    var updateDate: String?=""
  }