package com.inclusive.finance.bean

data class TongBuStandard(
    val baseCreateTime: String,
    val baseCreatorId: String,
    val baseModifierId: String,
    val baseModifyTime: String,
    val byReplaceNo: String,
    val categoryId: String,
    val categoryName: String,
    val classNo: String,
    val drafter: String,
    val editorDepartmentName: String,
    val filePath: String,
    val id: String,
    val isCollect: String,
    val keywords: String,
    val name: String,
    val no: String,
    val pages: String,
    val ratifyDepartmentName: String,
    val references: String,
    val releaseTime: String,
    val remark: String,
    val replaceNo: String,
    val sameClassNo: Any,
    val sameTopicNo: String,
    val sourceId: String,
    val sourceName: String,
    val standards: Any,
    val startDepartmentName: String,
    val startTime: String,
    val status: String
)